config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  root "patients#index"
  get "/graphs", to: "patients#graph"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
    enum gender: {'Male': 0, 'Female': 1, 'Other': 2}
    enum blood_group: { 'A+':0, 'A-':1,'B+':2, 'B-':3, 'O+':4, 'O-':5,'AB+':6, 'AB-':7 }
    enum marital_status: {'Single': 0, 'Married': 1, 'Widowed': 2, 'Divorced': 3, 'Seperated': 4}
    validates :mobile_number,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 } 
    validates :first_name, :last_name,:date_of_birth, :diagnosis,:presence=>true               
    def full_name
        [first_name, last_name].compact.join(' ')
    end                  
    before_create :set_op_number
    private
    def set_op_number
        number = SecureRandom.random_number(10000)
        new_op_number = "OP#{number}"
        self.op_number = new_op_number
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:receptionist, :doctor]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  include Pundit::Authorization
  allow_browser versions: :modern
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end

  private

  def user_not_authorized(exception)
    flash[:alert] = "You are not authorized to access this resource."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!  # Ensure user is authenticated
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.page(params[:page]).per(10).order("created_at DESC")
    authorize @patients
  end

  def graph
    @patients = Patient.all
    authorize @patients
  end


  # GET /patients/1 or /patients/1.json
  def show
    authorize @patient
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    authorize @patient
  end

  # GET /patients/1/edit
  def edit
    authorize @patient
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)
    authorize @patient
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    authorize @patient
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    authorize @patient
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_path, status: :see_other, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :date_of_birth, :blood_group, :gender, :mobile_number, :occupation, :marital_status, :weight, :height, :diagnosis, :op_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">PORTAL</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <% if current_user %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Patients",patients_path, :class=>"nav-link active" %>
        </li>
        <% if current_user.doctor? %>
        <li class="nav-item">
          <%= link_to "Graphs",graphs_path, :class=>"nav-link active" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="d-flex justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <p style="color:white;margin-top:10px;">Logged In As: <%= current_user.name.humanize %>(<%=current_user.role.humanize %>)</p>
        </li>
        <li class="nav-item">
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, :class=>"btn btn-primary", form: { turbolink: false}  %> 
        </li>
      </ul>
    </div>
    <%end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portal" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user.doctor? %>

       <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }  %>
     <% else %>
       <p>You are not signed in</p>
       <p>
         <%= link_to "Sign up", new_user_registration_path %><br>
         <%= link_to "Login", new_user_session_path %>
       </p>
     <% end %>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, :class=>"form-control form-control-lg" %>
  </div>

  <div class="col-md-6">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, :class=>"form-control form-control-lg" %>
  </div>
  </div>

  <div class="row">
  <div class="col-md-6">
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth, :class=>"form-control form-control-lg" %>
  </div>

  <div class="col-md-6">
    <%= form.label :blood_group, style: "display: block" %>
    <%= form.select :blood_group, Patient.blood_groups.keys,{},{:class => 'form-control'} %>
  </div>
  </div>
<div class="row">
  <div class="col-md-6">
    <%= form.label :gender, style: "display: block" %>
    <%= form.select :gender, Patient.genders.keys ,{},{:class => 'form-control'}%>
  </div>

  <div class="col-md-6">
    <%= form.label :mobile_number, style: "display: block" %>
    <%= form.text_field :mobile_number, :class=>"form-control form-control-lg" %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= form.label :occupation, style: "display: block" %>
    <%= form.text_field :occupation , :class=>"form-control form-control-lg"%>
  </div>

  <div class="col-md-6">
    <%= form.label :marital_status, style: "display: block" %>
    <%= form.select :marital_status, Patient.marital_statuses.keys,{},{:class => 'form-control'} %>
  </div>
  </div>
<div class="row">
  <div class="col-md-6">
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight, :class=>"form-control form-control-lg" %>
  </div>

  <div class="col-md-6">
    <%= form.label :height, style: "display: block" %>
    <%= form.number_field :height, :class=>"form-control form-control-lg" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form.label :diagnosis, style: "display: block" %>
    <%= form.text_area :diagnosis, :class=>"form-control form-control-lg" %>
  </div>
  </div><br>

  <div class="col">
    <%= form.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div class="col-md-6 mx-auto">
<div class="card border-info">
  <div class="card-body">
    <h5 class="card-title text-primary"><%=@patient.full_name %></h5>
    <hr class="border border-primary border-3 opacity-75">
    <p class="card-text"><%= @patient.diagnosis %></p>
    
  <p>
    <strong>Blood group:</strong>
    <%= patient.blood_group %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= patient.gender %>
  </p>
<% if patient.date_of_birth.present? %>
  <p>
    <strong>Date of birth:</strong>
    <%= patient.date_of_birth.strftime("%d-%m-%Y")  %>
  </p>  
  <% end %>

  <p>
    <strong>Blood group:</strong>
    <%= patient.blood_group %>
  </p>
  <p>
    <strong>Mobile number:</strong>
    <%= patient.mobile_number %>
  </p>

  <p>
    <strong>Occupation:</strong>
    <%= patient.occupation %>
  </p>

  <p>
    <strong>Marital status:</strong>
    <%= patient.marital_status %>
  </p>
  
  <% if patient.weight.present? %>
  <p>
    <strong>Weight:</strong>
    <%= patient.weight %><span>kg</span>
  </p>
  <% end %>

  <% if patient.height.present? %>
  <p>
    <strong>Height:</strong>
    <%= patient.height %><span>cm</span>
  </p>
  <% end %>

  <p>
    <strong>Op number:</strong>
    <%= patient.op_number %>
  </p>

</div>
</div>

app/views/patients/edit.html.erb
<% content_for :title, "Edit Patient" %>
<div class="d-flex justify-content-end mt-4">
  <%= link_to "Back", patients_path, :class=>"btn btn-outline-info" %>
</div>

<h1>Editing patient</h1><br>

<%= render "form", patient: @patient %>

<br>

app/views/patients/graph.html.erb
<% if policy(@patients).graph? %>
    <%= line_chart Patient.group_by_day(:created_at).count %>
<% end %>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Patients" %>
<div class="d-flex justify-content-end">
<% if policy(@patients).new? %>
<%= link_to "Create Patient", new_patient_path, :class =>"btn btn-primary btn-lg" %>
<% end %>
</div><br>

<div id="patients">
<div class="table-responsive">
<table class="table table-primary table-hover">
<thead>
<tr>
  <th scope="col">ID</th>
  <th scope="col">FirstName</th>
  <th scope="col">LastName</th>
  <th></th>
</tr>
</thead>
<tbody>
<% @patients.each do |patient| %>
<tr>
<td><%=patient.id %></th>
<td><%=patient.first_name.humanize %></th>
<td><%=patient.last_name.humanize %></td>
<td>
<div class="btn-group">
<%= link_to "View", patient_path(patient), :class =>"btn btn-outline-primary btn-sm" %>
<% if policy(patient).edit? %>
  <%= link_to "Edit", edit_patient_path(patient), :class =>"btn btn-outline-success btn-sm" %>
  <%= button_to 'Delete', patient_path(patient), method: :delete, :class=>"btn btn-outline-danger btn-sm", form: { turbolink: false}  %> 
<% end %>
</div>
</td>
</tr>
<% end %>
</tbody>
</table>
<%= paginate @patients %>

</div>

app/views/patients/new.html.erb
<% content_for :title, "New patient" %>

<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<div class=" mt-4 d-flex justify-content-end">
  <%= link_to "Back", patients_path, class: "btn btn-outline-primary" %>
</div>

<div class="mt-4">
  <%= render @patient %>
</div>